language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

before_script:
  - git clone https://github.com/froydnj/archive ~/lisp/archive

script:
  - ros -s prove -e '(or (prove:run :qlot-test) (uiop:quit -1))'
