language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/travis-install.sh | sh

script:
  - cl -l prove -e '(or (prove:run :qlot-test) (uiop:quit -1))'
